### PR TITLE
Use commands connect / disconnect for logging in / out

### LINKED ISSUE #16: Follow Slack slash command style guide
Make sure to follow [Slack's style guide for slash commands](https://api.slack.com/tutorials/slash-commands-style-guide).

**Details:**
- [x] `/challonge login` -> `/challonge connect`
- [x] `/challonge logout` -> `/challonge disconnect`?
- [x] ~Use delayed responses for all messages that query ChallongeAPI? Might avoid the dreaded timeout errors from Slack.~

### PR DESCRIPTION
**Pull request by sebgrohn**
Follow [Slack's style guide for slash commands](https://api.slack.com/tutorials/slash-commands-style-guide). This PR takes care of the easy things such as naming of commands. Did I miss anything obvious?

Resolves #16.

### CODE REVIEW

**Comment by CurriedFloat** [comment]
Maybe this is out of scope and should be another issue, but what about their  **Help users help themselves with /command help**  Section?

**Comment by sebgrohn** [comment]
Which part of that section are you referring to? :) This one?

>If your slash command's actions are sophisticated enough to take arguments, it is wise to also enhance your help function to provide illumination on those actions: `/please help feed` and `/please help tease` ...

**Comment by CurriedFloat** [comment]
I guess I'm wondering if `/next help` works

**Comment by sebgrohn** [comment]
It sure does! :)

**Pull request merged**
