### PR TITLE
Refactor handlers with "pipeline" utility methods.

### PR DESCRIPTION
**Pull request by sebgrohn**
Take two of #37, without any Maybes, Eithers, or Futures. (Sign-up  command saved for another PR.)

### CODE REVIEW

**Comment by CurriedFloat** [comment]
Looks good!

Maybe the chains would read better with more named functions, `chain(validate, concurrenct(get1, get2), useCase)`.

**Comment by sebgrohn** [comment]
> Maybe the chains would read better with more named functions, `chain(validate, concurrenct(get1, get2), useCase)`.

Do you mean convert back from arrow to classic functions, and then name them? Like, for example:
```
const listOpenTournaments = chain(
    concurrent(
        tryGetUser,
        ({ challongeService }) => async function validateOpenTournaments() {
            const openTournaments = await challongeService.fetchOpenTournaments();
            // ...
        },
    ),
    () => function formatOpenTournaments({ user, openTournaments }) {
        return R.reduce(/* ... */)(openTournaments)
            .get();
    },
);
```

Yeah, that's probably an improvement. 👍 The only downside, I guess, is that arrow functions that are a single expression would need to be converted to a statement with `return`...

**Comment by CurriedFloat** [comment]
More like:
```
const tryGetOpenTournaments = arg => .... 

const listOpenTournaments = chain(
    concurrent(
        tryGetUser,
        tryGetOpenTournaments
    ),
   formatOpenTournaments
);
```

**Comment by sebgrohn** [comment]
Oh, now I see what you mean. :) I think for that to be more readable, we would need to split the handlers into separate files, though. That's something I'd like to do but maybe not part of this PR?

**Comment by CurriedFloat** [comment]
Agreed

**Pull request merged**
